quiz = [
    ("Quanto fa 2 + 2?", "4"),
    ("Capitale d'Italia?", "Roma"),
    ("Qual è il colore del cielo?", "blu"),
    ("La radice quadrata di 16?", "4"),
    ("Chi ha scritto I Promessi Sposi?", "Alessandro Manzoni"),
    ("Qual è il fiume più lungo del mondo?", "Il Nilo"),
    ("Chi era il capo del Terzo Reich durante la Seconda Guerra Mondiale?", "Adolf Hitler"),
    ("In che anno è stata scoperta l’America da Cristoforo Colombo?", "1492"),
    ("Qual è la capitale del Canada?", "Ottawa"),
    ("Qual è il monte più alto del mondo?", "Monte Everest"),
    ("Chi ha dipinto la Gioconda?", "Leonardo da Vinci"),
    ("Quando è avvenuta la Rivoluzione Francese?", "1789"),
    ("Qual è la formula chimica dell'acqua?", "H₂O"),
    ("Che cos’è la fotosintesi clorofilliana?", "Il processo attraverso cui le piante producono zuccheri usando luce solare, anidride carbonica e acqua"),
    ("Qual è la radice quadrata di 144?", "12"),
    ("Chi ha inventato il telefono?", "Alexander Graham Bell"),
    ("In quale continente si trova l’Argentina?", "America del Sud"),
    ("Quale metallo è simboleggiato con Fe nella tavola periodica?", "Ferro"),
    ("Quale città è famosa per il Colosseo?", "Roma"),
    ("Chi ha scritto la Divina Commedia?", "Dante Alighieri"),
    ("Dove si trova il deserto del Gobi?", "Tra Mongolia e Cina"),
    ("Quale animale è noto come il “re della foresta”?", "Il leone"),
    ("Qual è l’organo principale del sistema circolatorio umano?", "Il cuore"),
    ("Qual è la lingua ufficiale del Brasile?", "Portoghese"),
    ("Quante regioni ha l’Italia?", "20"),
    ("Chi ha unificato l’Italia nel XIX secolo?", "Giuseppe Garibaldi"),
    ("Qual è il numero π (pi greco) approssimato ai primi tre decimali?", "3,141"),
    ("Qual è il paese più popoloso del mondo?", "Cina"),
    ("Chi è l’autore del Decameron?", "Giovanni Boccaccio"),
    ("Che cos’è stata la Guerra Fredda?", "Un conflitto ideologico e politico tra Stati Uniti e Unione Sovietica, senza guerra diretta"),
    ("Qual è il simbolo chimico dell’ossigeno?", "O"),
    ("In quale città si trova la Torre Eiffel?", "Parigi"),
    ("Chi ha scritto Romeo e Giulietta?", "William Shakespeare"),
    ("Che cosa indica l’acronimo ONU?", "Organizzazione delle Nazioni Unite"),
]